// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TestCase_1_Iphone11_Amazon', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TestCase_1_Iphone11_Amazon', async function() {
	//Test starts with loading google.com
    await driver.get("https://www.google.com/")
    await driver.manage().window().setRect(1936, 1014)
    await driver.findElement(By.name("q")).click()
    await driver.findElement(By.name("q")).click()
	//Search for amazon.com
    await driver.findElement(By.name("q")).sendKeys("amazon.com")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("div:nth-child(1) > .rc .LC20lb > span")).click()
    await driver.findElement(By.id("twotabsearchtextbox")).click()
	//Search for 'iphone 11'
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("iphone 11")
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("iPhone 11")).click()
    await driver.findElement(By.css(".qa-title-text")).click()
    assert(await driver.findElement(By.css(".qa-title-text")).getText() == "Apple iPhone 11 (64GB, Purple) [Locked] + Carrier Subscription")
	//Store NameofWebsite, NameofProduct and PriceOfProduct
	vars["NameOfWebsite"] = await driver.getTitle()
    vars["NameofProduct"] = await driver.findElement(By.linkText("iPhone 11")).getText()
    vars["PriceofProduct"] = await driver.findElement(By.css(".planPriceText")).getText()
	
	
  })
})
