// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TestCase_1_Iphone11_Lazada', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TestCase_1_Iphone11_Lazada', async function() {
    //Test starts with loading google.com
	await driver.get("https://www.google.com/")
    await driver.manage().window().setRect(1936, 1014)
    await driver.findElement(By.name("q")).click()
    //Search for lazada.com.my
	await driver.findElement(By.name("q")).sendKeys("lazada.com.my")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("div:nth-child(1) > .rc .LC20lb > span")).click()
    {
      const element = await driver.findElement(By.linkText("Voucher"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
	//Search for 'iphone 11'
    await driver.findElement(By.id("q")).click()
    await driver.findElement(By.id("q")).sendKeys("iphone 11")
    await driver.findElement(By.id("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".c3wo-b")).click()
    assert(await driver.findElement(By.css(".c1DXz4 > span:nth-child(2)")).getText() == "iphone 11")
	//Store NameofWebsite, NameofProduct and PriceOfProduct
	vars["NameOfWebsite"] = await driver.getTitle()
	vars["NameOfProduct"] = await driver.findElement(By.linkText("Apple iphone 11 Pro Max 64g/256g Used Fullset (One Year Warranty)")).getText()
    vars["PriceOfProduct"] = await driver.findElement(By.css(".pdp-price")).getText()
  })
})
